// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD37tfGkBrjdshsnMWgxmZBxb45wb87hJY',
    appId: '1:1078765675204:web:691762c39f68c482041f91',
    messagingSenderId: '1078765675204',
    projectId: 'annur2app',
    authDomain: 'annur2app.firebaseapp.com',
    databaseURL: 'https://annur2app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'annur2app.appspot.com',
    measurementId: 'G-W6QLD0SQK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcCmTQtI3Z0z7Ss2_5FTc8KYlzFtG2Mq0',
    appId: '1:1078765675204:android:472c06f84ead7eb8041f91',
    messagingSenderId: '1078765675204',
    projectId: 'annur2app',
    databaseURL: 'https://annur2app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'annur2app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrcyyvoTRKiO0WqNoaLXZFURCW7VIiDnQ',
    appId: '1:1078765675204:ios:1ba2f907539a69ec041f91',
    messagingSenderId: '1078765675204',
    projectId: 'annur2app',
    databaseURL: 'https://annur2app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'annur2app.appspot.com',
    iosBundleId: 'com.miniawradsantri.awrad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrcyyvoTRKiO0WqNoaLXZFURCW7VIiDnQ',
    appId: '1:1078765675204:ios:1ba2f907539a69ec041f91',
    messagingSenderId: '1078765675204',
    projectId: 'annur2app',
    databaseURL: 'https://annur2app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'annur2app.appspot.com',
    iosBundleId: 'com.miniawradsantri.awrad',
  );
}
